# Generated by Django 5.1.7 on 2025-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
