# Generated by Django 5.1.7 on 2025-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investapp', '0002_investment_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='btc_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
